#!/usr/bin/env node

const { OpenAI } = require('openai');
const fs = require('fs').promises;
const path = require('path');

async function testMinimal() {
  try {
    console.log('🤖 Starting minimal AI test...');
    
    // Test OpenAI connection
    const openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
    
    console.log('📡 Testing OpenAI connection...');
    
    const completion = await openai.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages: [
        {
          role: "user",
          content: "Write a short test message (just 2 sentences) about organizational change."
        }
      ],
      max_tokens: 100
    });

    const content = completion.choices[0].message.content;
    console.log('✅ OpenAI response received:', content);
    
    // Test file creation
    const testContent = `---
title: 'Test AI Generated Post'
description: 'A test post generated by AI'
pubDate: '2024-12-11'
heroImage: '/blog-placeholder-1.jpg'
tags: ['test', 'ai']
---

${content}`;

    const filename = 'test-ai-post.md';
    const filepath = path.join('../../apps/blog/src/content/drafts', filename);
    
    console.log('📝 Writing test file to:', filepath);
    await fs.writeFile(filepath, testContent, 'utf8');
    
    console.log('✅ Test file created successfully!');
    
    // Set GitHub Actions output
    const outputFile = process.env.GITHUB_OUTPUT;
    if (outputFile) {
      await fs.appendFile(outputFile, `test_success=true\n`);
      await fs.appendFile(outputFile, `test_file=${filename}\n`);
    }
    
  } catch (error) {
    console.error('❌ Test failed:', error);
    
    const outputFile = process.env.GITHUB_OUTPUT;
    if (outputFile) {
      await fs.appendFile(outputFile, `test_success=false\n`);
      await fs.appendFile(outputFile, `error_message=${error.message}\n`);
    }
    
    process.exit(1);
  }
}

testMinimal();