name: Autonomous Roadmap Agent

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Specific issue number to work on (optional)'
        required: false
        type: string
      priority:
        description: 'Priority filter (HP, MP, LP)'
        required: false
        type: string
        default: 'HP'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  implement-roadmap-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.1

      - name: Install dependencies
        run: |
          cd .github/scripts
          pnpm install

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run autonomous agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ inputs.issue_number }}
          PRIORITY_FILTER: ${{ inputs.priority }}
        run: |
          node .github/scripts/autonomous-agent.js

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: implement roadmap task via autonomous agent"
          branch: automated/roadmap-implementation-${{ github.run_number }}
          delete-branch: true
          title: "🤖 [Auto] Implement roadmap task"
          body: |
            ## Automated Implementation
            
            This PR was automatically generated by the autonomous agent.
            
            **Generated**: ${{ github.run_number }}
            **Timestamp**: ${{ github.event.head_commit.timestamp }}
            
            Please review changes carefully before merging.
          labels: |
            automated
            roadmap
          draft: false
